#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
EEC "Two Worlds" — 30-MINUTE EPISODE GENERATOR (serialized "learn with fun").

Upgrades the old 2-min generator into a professional long-form engine: a
multi-act serialized drama that TEACHES without feeling like a lesson. Each
episode ~4500-6000 words (~25-35 min spoken), built ACT BY ACT so it stays
coherent AND fits Gemini's free-tier pacing (each act is one call; resumable).

STRUCTURE (the "sandwich that teaches"):
  cold_open   - drop into a dramatic hook / mini-cliffhanger tease (Macal/Nour)
  coach_intro - Coach (Egyptian AR): "today watch for these phrases..."
  act1        - real scene, natural level-appropriate English, plot advances
  coach_break1- Coach unpacks the key phrases from act1 + a common mistake
  act2        - complication / drama, more English in context
  coach_break2- Coach: more phrases + a culture note
  act3        - resolution + a CLIFFHANGER for next week
  coach_outro - recap the phrases, a community challenge, subscribe CTA

Every line is tagged: {section, speaker, lang, text}. speaker must be a CAST id
(Coach, Macal, Nour, TaxiDriver, Barista, Landlord, Interviewer, Friend_M,
Friend_F, Official) so the synth routes it to the right voice. Coach lines are
Egyptian Arabic; story lines are English (natural, level-appropriate).

Continuity: season.json holds story-so-far + phrases-taught + current episode.
Difficulty scales across the season (A2 -> B1 -> B2).

Output: episodes/epNN/script.json (same contract the synth + assembly consume).

Usage: GEMINI_API_KEY=... python3 gen_episode.py --episode 1 [--level A2]
                                    [--out episodes/ep01/script.json]
Resumable: partial acts are cached in episodes/epNN/_acts/ so a quota stall
doesn't lose work; re-run to continue.
"""
import os, sys, json, re, argparse, time, urllib.request

MODEL = os.environ.get("EEC_SCRIPT_MODEL", "gemini-3.6-flash")
HOME = os.environ.get("EEC_PODCAST_HOME", "/opt/eec-podcast")
SEASON_PATH = os.path.join(HOME, "season.json")

CAST_IDS = ["Coach", "Macal", "Nour", "TaxiDriver", "Barista", "Landlord",
            "Interviewer", "Friend_M", "Friend_F", "Official"]

SEASON1 = [
    (1, "The Arrival", "A2", "airport + taxi: first steps in Dubai, small talk, directions"),
    (2, "The Apartment", "A2", "the landlord: numbers, requests, complaints, settling in"),
    (3, "The Coffee Order", "A2", "the fast-talking barista catches Macal off guard"),
    (4, "The Interview", "B1", "the big job interview — nerves, questions, first impression"),
    (5, "First Day", "B1", "meeting the team, introductions, office small talk"),
    (6, "The Misunderstanding", "B1", "Macal says the wrong thing; recovering politely"),
    (7, "Making a Friend", "B1", "social English, humor, a real connection"),
    (8, "The Meeting", "B2", "speaking up at work, giving an opinion under pressure"),
    (9, "The Phone Call", "B2", "a tricky service call, no visual cues, staying calm"),
    (10, "The Presentation", "B2", "the season payoff — Macal presents, everything on the line"),
]

# the acts, in order, each generated by one Gemini call
ACTS = [
    ("cold_open",    "a 60-90 second COLD OPEN: drop the listener into a tense/curious moment near the episode's climax, then pull back. 2-4 short story lines (Macal/Nour or a guest). Create a HOOK that makes them need to keep listening."),
    ("coach_intro",  "the COACH INTRO (Egyptian Arabic, Coach only): warmly welcome the listener, set today's situation, and tell them the 2-3 English phrases to listen for. 3-5 lines. Warm, fun, encouraging — never dry."),
    ("act1",         "ACT 1 (the main story, 12-18 lines): the situation unfolds in natural {level} English between Macal and the guest(s). Real, human, a little funny. Plot advances. Weave in the target phrases naturally."),
    ("coach_break1", "COACH BREAK 1 (Egyptian Arabic, Coach): pause the story to unpack 2 key English phrases from Act 1 (what they mean, when to use them) + 1 common mistake learners make. 4-6 lines. Warm teacher energy."),
    ("act2",         "ACT 2 (12-18 lines): a complication or twist raises the stakes. More natural {level} English in context. Emotion — that's what makes it memorable."),
    ("coach_break2", "COACH BREAK 2 (Egyptian Arabic, Coach): 1-2 more phrases + a quick culture note about life/English in Dubai/the Gulf. 4-6 lines."),
    ("act3",         "ACT 3 (10-16 lines): the situation resolves for now — a small win or a surprise — and END ON A CLIFFHANGER that sets up next episode. Natural {level} English."),
    ("coach_outro",  "the COACH OUTRO (Egyptian Arabic, Coach): recap the episode's phrases, give a fun community CHALLENGE for the Telegram group, and a warm subscribe CTA + tease next episode. 3-5 lines."),
]


def load_season():
    try:
        with open(SEASON_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"season": 1, "current_episode": 1,
                "story_so_far": ("Macal is an ambitious young Egyptian who just moved to "
                                 "Dubai to build a new life. He's warm and determined but "
                                 "nervous about his English. Nour is a confident friend "
                                 "already settled in Dubai who helps him. The Coach is the "
                                 "warm Egyptian-Arabic teacher voice guiding the audience."),
                "phrases_taught": []}


def save_season(s):
    os.makedirs(os.path.dirname(SEASON_PATH), exist_ok=True)
    with open(SEASON_PATH, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False, indent=2)


def call_gemini(prompt, api_key, temp=0.95):
    url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
           f"{MODEL}:generateContent?key={api_key}")
    body = {"contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": temp, "response_mime_type": "application/json"}}
    req = urllib.request.Request(url, data=json.dumps(body).encode("utf-8"),
                                headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=180) as r:
        data = json.loads(r.read().decode("utf-8"))
    return data["candidates"][0]["content"]["parts"][0]["text"]


def extract_json(raw):
    raw = raw.strip().replace("```json", "").replace("```", "").strip()
    try:
        return json.loads(raw)
    except Exception:
        m = re.search(r"\{[\s\S]*\}|\[[\s\S]*\]", raw)
        if m:
            return json.loads(m.group(0))
        raise


def act_prompt(ep, title, level, situation, act_key, act_desc, season, prev_lines):
    prev = ""
    if prev_lines:
        prev = "STORY SO FAR IN THIS EPISODE (continue naturally, do not repeat):\n" + \
               "\n".join(f"[{l['section']}][{l['speaker']}] {l['text']}" for l in prev_lines[-14:])
    return f"""You are the head writer for "Two Worlds", a serialized bilingual English-learning
DRAMA podcast by Empire English Community for Egyptian/Arab learners. Mission:
LEARN WITH FUN — a story so good people binge it, that teaches English by living it.

BRAND VOICE: warm, honest, encouraging. NEVER "hack/secret/guaranteed" or shaming.
Egyptian Arabic for the Coach; natural, native, level-appropriate English for the story.

CHARACTERS (use ONLY these speaker ids): {", ".join(CAST_IDS)}.
- Macal: Egyptian learner-hero in Dubai; English is natural but improving.
- Nour: confident friend already settled in Dubai; warm, encouraging.
- Coach: NOT in the story — the Egyptian-Arabic voice that teaches the audience.
- Guests by role: TaxiDriver, Barista, Landlord, Interviewer, Friend_M, Friend_F, Official.

EPISODE {ep}: "{title}" — CEFR level {level}. Situation: {situation}.
SEASON STORY SO FAR: {season.get('story_so_far','')}

{prev}

WRITE ONLY THIS SECTION: {act_key} — {act_desc.format(level=level)}

Return STRICT JSON only: a list of line objects, each:
{{"section":"{act_key}","speaker":"<one of the cast ids>","lang":"en" or "ar","text":"..."}}
Rules: Coach lines are ALWAYS lang "ar" (Egyptian Arabic). Story lines are lang "en".
Keep English at level {level}. Natural spoken lines (contractions, real reactions).
No markdown, no commentary — just the JSON list of lines for THIS section."""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--episode", type=int, required=True)
    ap.add_argument("--level", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: set GEMINI_API_KEY", file=sys.stderr); sys.exit(2)

    ep = args.episode
    plan = next((p for p in SEASON1 if p[0] == ep), None)
    if not plan:
        print(f"ERROR: no plan for episode {ep}", file=sys.stderr); sys.exit(2)
    _, title, level, situation = plan
    level = args.level or level
    season = load_season()

    ep_dir = os.path.join(HOME, "episodes", f"ep{ep:02d}")
    acts_dir = os.path.join(ep_dir, "_acts")
    os.makedirs(acts_dir, exist_ok=True)

    all_lines = []
    for act_key, act_desc in ACTS:
        cache = os.path.join(acts_dir, f"{act_key}.json")
        if os.path.exists(cache):  # resume: reuse already-generated acts
            lines = json.load(open(cache, encoding="utf-8"))
            all_lines += lines
            print(f"  [{act_key}] cached ({len(lines)} lines)")
            continue
        prompt = act_prompt(ep, title, level, situation, act_key, act_desc, season, all_lines)
        lines = None
        for attempt in range(1, 5):
            try:
                lines = extract_json(call_gemini(prompt, api_key))
                assert isinstance(lines, list) and lines
                # tag/validate
                for ln in lines:
                    ln["section"] = act_key
                    ln.setdefault("lang", "ar" if ln.get("speaker") == "Coach" else "en")
                    if ln.get("speaker") == "Coach":
                        ln["lang"] = "ar"
                break
            except Exception as e:
                print(f"  [{act_key}] attempt {attempt}: {str(e)[:80]}", file=sys.stderr)
                lines = None
                time.sleep(min(6 * attempt, 30))
        if not lines:
            print(f"  [{act_key}] FAILED — re-run to resume from here.", file=sys.stderr)
            sys.exit(1)
        json.dump(lines, open(cache, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        all_lines += lines
        words = sum(len(l["text"].split()) for l in all_lines)
        print(f"  [{act_key}] +{len(lines)} lines (total {len(all_lines)}, ~{words} words)")
        time.sleep(1)

    # assemble the episode script (same contract as before)
    script = {
        "episode": ep, "title": title, "level": level,
        "lines": all_lines,
        "phrase_of_episode": {"en": "", "ar": ""},  # filled by a final pass or editor
        "word_count": sum(len(l["text"].split()) for l in all_lines),
        "cast_used": sorted({l["speaker"] for l in all_lines}),
    }
    out = args.out or os.path.join(ep_dir, "script.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    json.dump(script, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=2)

    # update season memory
    season["story_so_far"] = (season.get("story_so_far", "") +
                              f" [Ep{ep}: {title} — see script]").strip()[-1500:]
    season["current_episode"] = ep + 1
    save_season(season)

    est_min = round(script["word_count"] / 150, 1)  # ~150 wpm spoken
    print(f"\nOK wrote {out}")
    print(f"  {len(all_lines)} lines, ~{script['word_count']} words (~{est_min} min spoken)")
    print(f"  cast used: {script['cast_used']}")


if __name__ == "__main__":
    main()
